const wordData = [
    { word: "airline", meaning: "n.航空公司", example: "I booked my flight with a reputable airline. 我通过一家信誉良好的航空公司预订了航班。" },
    { word: "bay", meaning: "n.(海或湖的)湾", example: "We sailed into the calm bay at sunset. 日落时分，我们驶入了平静的海湾。" },
    { word: "craft", meaning: "n.手艺;工艺;技艺", example: "She learned the craft of pottery from her grandmother. 她从祖母那里学到了陶艺手艺。" },
    { word: "antique", meaning: "n.古物;古董 a.古老的", example: "This antique vase is worth a fortune. 这个古董花瓶价值连城。" },
    { word: "pleasant", meaning: "a.令人愉快的;友好的", example: "The weather was pleasant during our picnic. 我们野餐时天气非常宜人。" },
    { word: "arise", meaning: "vi.起身;出现;由…引起", example: "New challenges arise every day in this job. 这份工作每天都会出现新的挑战。" },
    { word: "massive", meaning: "a.巨大的;非常严重的", example: "The earthquake caused massive damage to the city. 地震对城市造成了巨大的破坏。" },
    { word: "literally", meaning: "ad.字面上;真正地", example: "He was literally jumping for joy. 他真的是高兴得跳了起来。" },
    { word: "breath", meaning: "n.呼吸的空气", example: "She took a deep breath before speaking. 她在说话前深吸了一口气。" },
    { word: "take sb's breath away", meaning: "令人惊叹", example: "The view from the mountaintop took my breath away. 山顶的景色让我惊叹不已。" },
    { word: "bound", meaning: "a.准备前往(某地);一定会", example: "The train is bound for New York. 这列火车是开往纽约的。" },
    { word: "scenery", meaning: "n.风景;景色", example: "The scenery along the coast is breathtaking. 沿海的风景令人叹为观止。" },
    { word: "awesome", meaning: "a.令人惊叹的;可怕的", example: "The fireworks display was truly awesome. 烟花表演真是令人惊叹。" },
    { word: "spectacular", meaning: "a.壮观的;壮丽的n.壮丽场面", example: "We watched a spectacular sunset over the ocean. 我们观赏了海上壮观的日落。" },
    { word: "peak", meaning: "n.顶峰;山峰;尖形", example: "The climbers reached the peak at dawn. 登山者在黎明时分登顶。" },
    { word: "highlight", meaning: "n.最好的部分 vt.突出;强调", example: "The highlight of the trip was visiting the ancient temple. 这次旅行的亮点是参观那座古老的寺庙。" },
    { word: "goat", meaning: "n.山羊", example: "The farmer keeps goats for milk and cheese. 这位农民养山羊是为了获取羊奶和奶酪。" },
    { word: "grizzly bear", meaning: "n.灰熊", example: "We saw a grizzly bear in the national park. 我们在国家公园里看到了一只灰熊。" },
    { word: "drill", meaning: "vi.&vt.钻孔;打眼 n.钻头", example: "The workers drilled a hole in the wall. 工人们在墙上钻了一个洞。" },
    { word: "freezing", meaning: "a.极冷的;冰冻的", example: "It was freezing outside, so we stayed indoors. 外面非常冷，所以我们待在室内。" },
    { word: "freezing cold", meaning: "极冷的;冻僵的", example: "The water was freezing cold, but he still went for a swim. 水冰冷刺骨，但他还是去游泳了。" },
    { word: "freeze", meaning: "vi.&vt.结冰;(使)冻住", example: "The lake freezes over in winter. 冬天湖面会结冰。" },
    { word: "mall", meaning: "n.购物商场;购物广场", example: "We spent the afternoon shopping at the mall. 我们在购物中心逛了一下午。" },
    { word: "prairie", meaning: "n.北美草原", example: "The prairie stretched as far as the eye could see. 草原一望无际。" },
    { word: "anticipate", meaning: "vt.预料;预见;期望", example: "We didn't anticipate such a long delay. 我们没有预料到会耽搁这么久。" },
    { word: "bunch", meaning: "n.束;串;捆", example: "She gave me a bunch of flowers for my birthday. 她送了我一束花作为生日礼物。" },
    { word: "a bunch of", meaning: "一束;一串;一群;大量", example: "A bunch of kids were playing in the park. 一群孩子在公园里玩耍。" },
    { word: "thunder", meaning: "vi.打雷;轰隆隆地响 n.雷声", example: "The thunder roared loudly during the storm. 暴风雨中雷声轰鸣。" },
    { word: "frost", meaning: "n.霜;严寒天气 vt.使蒙上霜", example: "The grass was covered with frost in the morning. 早晨草地上覆盖了一层霜。" },
    { word: "curtain", meaning: "n.窗帘", example: "She drew the curtains to let in some light. 她拉开窗帘让光线照进来。" },
    { word: "border", meaning: "n.国界;边界(地区)", example: "We crossed the border into Canada. 我们越过边境进入了加拿大。" },
    { word: "duration", meaning: "n.持续时间;期间", example: "The duration of the movie is two hours. 这部电影的时长是两小时。" },
    { word: "harbour", meaning: "n.(海)港;港口", example: "The ship sailed into the harbour at dawn. 船在黎明时分驶入港口。" },
    { word: "enrol", meaning: "vi.&vt.(使)加入;注册;登记", example: "She decided to enrol in a cooking class. 她决定报名参加烹饪课程。" },
    { word: "quarry", meaning: "n.采石场", example: "The old quarry is now a popular swimming spot. 这个旧采石场现在是一个受欢迎的游泳地点。" },
    { word: "idiom", meaning: "n.习语;成语", example: "Learning idioms can be challenging for language learners. 学习习语对语言学习者来说可能很有挑战性。" },
    { word: "contrary", meaning: "a.相反的 n.相反的事实", example: "Contrary to popular belief, bats are not blind. 与普遍的看法相反，蝙蝠并不瞎。" },
    { word: "contrary to", meaning: "相反的;相对立的", example: "Contrary to expectations, the event was a success. 与预期相反，这次活动取得了成功。" },
    { word: "anyhow", meaning: "ad.(结束交谈)不过;反正", example: "Anyhow, I think we should give it a try. 不管怎样，我认为我们应该试一试。" },
    { word: "alongside", meaning: "prep.在…旁边 ad.在旁边", example: "She worked alongside her colleagues on the project. 她和同事们一起完成了这个项目。" },
    { word: "proceed", meaning: "vi.行进;继续做", example: "After the interruption, the speaker proceeded with his speech. 被打断后，演讲者继续他的讲话。" },
    { word: "proceed to sth.", meaning: "进而做(参加)", example: "After dinner, we proceeded to the living room for coffee. 晚餐后，我们到客厅喝咖啡。" },
    { word: "shore", meaning: "n.岸;滨", example: "We walked along the shore collecting seashells. 我们沿着海岸边走边捡贝壳。" },
    { word: "astonish", meaning: "vi.使十分惊讶;使吃惊", example: "His sudden appearance astonished everyone. 他的突然出现让所有人都感到惊讶。" },
    { word: "misty", meaning: "a.多雾的;模糊的", example: "The morning was misty, making it hard to see. 早晨雾气蒙蒙，视线模糊。" },
    { word: "mist", meaning: "n.薄雾;水汽", example: "The mist cleared as the sun rose. 太阳升起时，薄雾散去了。" },
    { word: "steel", meaning: "n.钢;钢铁工业", example: "The bridge is made of steel and concrete. 这座桥是用钢筋和混凝土建造的。" },
    { word: "dusk", meaning: "n.黄昏;傍晚", example: "We arrived at the village at dusk. 我们在黄昏时分到达了村庄。" },
    { word: "advertisement", meaning: "n.广告;启事", example: "I saw an advertisement for the job in the newspaper. 我在报纸上看到了这份工作的广告。" },
    { word: "accent", meaning: "n.口音", example: "She has a strong British accent. 她有很重的英国口音。" },
    { word: "photographer", meaning: "n.摄影师;拍照者", example: "The photographer took some amazing shots of the sunset. 摄影师拍了一些日落的精彩照片。" },
    { word: "owe", meaning: "vt.欠(账、债、情等)", example: "I owe him a favor for helping me move. 我欠他一个人情，因为他帮我搬了家。" },
    { word: "owe sth. to sb.", meaning: "欠(某人情);把…归功某人", example: "I owe my success to my parents' support. 我的成功归功于父母的支持。" },
    { word: "toast", meaning: "n.烤面包片;干杯 vt.干杯", example: "We raised our glasses for a toast. 我们举杯干杯。" },
    { word: "cobblestone", meaning: "a.铺有鹅卵石的", example: "The old town's streets are paved with cobblestones. 老城的街道铺着鹅卵石。" },
    { word: "coherent", meaning: "a.有条理的;清楚易懂的", example: "Her argument was clear and coherent. 她的论点清晰且有逻辑。" },
    { word: "technique", meaning: "n.技能;技术;技艺", example: "He has mastered the technique of oil painting. 他掌握了油画技巧。" },
    { word: "leaflet", meaning: "n.散页印刷品;传单;小册子", example: "They handed out leaflets about the event. 他们分发了关于活动的传单。" },
    { word: "organ", meaning: "n.(人或动植物的)器官", example: "The heart is a vital organ. 心脏是一个重要器官。" },
    { word: "toxin", meaning: "n.毒素(细菌产生致病物质)", example: "Some plants produce toxins to protect themselves. 一些植物会产生毒素来保护自己。" },
    { word: "ray", meaning: "n.光线;光束;(热/电)射线", example: "A ray of sunlight shone through the window. 一束阳光透过窗户照进来。" },
    { word: "sense of touch", meaning: "触觉", example: "The sense of touch helps us interact with the world. 触觉帮助我们与世界互动。" },
    { word: "radiation", meaning: "n.辐射;放射线", example: "Exposure to high levels of radiation can be harmful. 暴露在高辐射水平下可能有害。" },
    { word: "acid", meaning: "n.酸 a.酸的;酸性的", example: "Vinegar contains acetic acid. 醋中含有乙酸。" },
    { word: "millimetre", meaning: "n.毫米;千分之一米", example: "The gap was only a few millimetres wide. 这个缝隙只有几毫米宽。" },
    { word: "minor", meaning: "a.较小的;次要的;轻微的", example: "He suffered a minor injury in the accident. 他在事故中受了轻伤。" },
    { word: "layer", meaning: "n.层;表层;层次", example: "The cake has multiple layers of cream. 这个蛋糕有多层奶油。" },
    { word: "electric", meaning: "a.电的;用电的;电动的", example: "The car runs on electric power. 这辆车是电动的。" },
    { word: "electric shock", meaning: "触电;电击", example: "He got an electric shock from the faulty wire. 他被漏电的电线电了一下。" },
    { word: "victim", meaning: "n.受害者;患者", example: "The victim was taken to the hospital immediately. 受害者被立即送往医院。" },
    { word: "swollen", meaning: "a.(身体部位)肿起的;肿胀的", example: "Her ankle was swollen after the fall. 摔倒后她的脚踝肿了。" },
    { word: "swell", meaning: "vi.膨胀;肿胀", example: "His knee began to swell after the injury. 受伤后他的膝盖开始肿胀。" },
    { word: "blister", meaning: "n.(皮肤)水疱;(金属)气泡", example: "She got a blister from wearing new shoes. 她因为穿新鞋磨出了水疱。" },
    { word: "underneath", meaning: "prep.&ad.在…底下", example: "The cat hid underneath the table. 猫躲在桌子底下。" },
    { word: "nerve", meaning: "n.神经", example: "The doctor tested the patient's nerve responses. 医生测试了病人的神经反应。" },
    { word: "fabric", meaning: "n.织物;布料;(社会等)结构", example: "This fabric is soft and comfortable. 这种布料柔软舒适。" },
    { word: "loose", meaning: "a.松的;未系紧的;宽松的", example: "The screw is loose and needs tightening. 螺丝松了，需要拧紧。" },
    { word: "urgent", meaning: "a.紧急的;急迫的;急切的", example: "There was an urgent call for help. 有一个紧急的求助电话。" },
    { word: "ease", meaning: "v.(使)宽慰;减轻 n.容易", example: "The medicine helped ease the pain. 药物帮助缓解了疼痛。" },
    { word: "paramedic", meaning: "n.急救医生;护理人员", example: "The paramedic arrived quickly at the scene. 急救医生迅速赶到了现场。" },
    { word: "swallow", meaning: "vt.&vi.吞下;咽下", example: "She swallowed the pill with a glass of water. 她用一杯水吞下了药片。" },
    { word: "wrap", meaning: "v1.包、裹;(用手臂等)围住", example: "He wrapped the gift in colorful paper. 他用彩纸包好了礼物。" },
    { word: "bathtub", meaning: "n.浴缸;浴盆", example: "She relaxed in the bathtub after a long day. 漫长的一天后，她在浴缸里放松。" },
    { word: "bath", meaning: "n.洗澡 vt.给…洗澡", example: "The baby enjoys his bath time. 宝宝喜欢洗澡时间。" },
    { word: "slip", meaning: "vi.滑倒;滑落 n.滑倒", example: "He slipped on the wet floor. 他在湿滑的地板上滑倒了。" },
    { word: "mosquito", meaning: "n.蚊子", example: "Mosquitoes are common in tropical areas. 蚊子在热带地区很常见。" },
    { word: "elderly", meaning: "a.年纪较大的;上了年纪的", example: "The elderly man walked slowly with a cane. 这位老人拄着拐杖慢慢走。" },
    { word: "carpet", meaning: "n.地毯", example: "The living room has a soft, red carpet. 客厅铺着一张柔软的红色地毯。" },
    { word: "operator", meaning: "n.电话接线员;操作员", example: "The operator connected me to the right department. 接线员帮我转接到了正确的部门。" },
    { word: "ambulance", meaning: "n.救护车", example: "An ambulance rushed the injured to the hospital. 救护车将伤者紧急送往医院。" },
    { word: "delay", meaning: "v.推迟;延期;耽误 n.延误", example: "The flight was delayed due to bad weather. 航班因恶劣天气延误了。" },
    { word: "needle", meaning: "n.针;缝衣针;注射针;指针", example: "The nurse used a sterile needle for the injection. 护士使用了一根无菌针头进行注射。" },
    { word: "IV needle", meaning: "静脉注射针", example: "The doctor inserted an IV needle into the patient's arm. 医生将静脉注射针插入病人的手臂。" },
    { word: "vital sign", meaning: "生命体征", example: "The nurse checked the patient's vital signs. 护士检查了病人的生命体征。" },
    { word: "ward", meaning: "n.病房", example: "She was moved to a private ward. 她被转到了私人病房。" },
    { word: "drown", meaning: "vi.&vt.(使)淹死;溺死;浸泡", example: "The lifeguard saved the child from drowning. 救生员救了那个溺水的孩子。" },
    { word: "sprain", meaning: "vt.扭伤(关节) n.扭伤", example: "He sprained his ankle while playing basketball. 他在打篮球时扭伤了脚踝。" },
    { word: "ankle", meaning: "n.踝;踝关节", example: "She wore a brace to support her weak ankle. 她戴了一个护具来支撑她脆弱的脚踝。" },
    { word: "bleeding", meaning: "n.流血;失血", example: "The bleeding stopped after applying pressure. 按压后，流血止住了。" },
    { word: "bleed", meaning: "vi.流血;失血", example: "The wound continued to bleed for a while. 伤口持续流了一会儿血。" },
    { word: "panic", meaning: "vi.&vt.(使)惊慌 n.惊恐", example: "She panicked when she couldn't find her phone. 她找不到手机时惊慌失措。" },
    { word: "interrupt", meaning: "vi.&v.打断;打扰 vt.使暂停", example: "Please don't interrupt me while I'm speaking. 我说话时请不要打断我。" },
    { word: "scream", meaning: "v.(因愤怒等)高声喊 n.尖叫", example: "The child screamed when he saw the spider. 孩子看到蜘蛛时尖叫起来。" },
    { word: "fellow", meaning: "a.同类的;同事的 n.男人", example: "He is a fellow student in my class. 他是我班上的同学。" },
    { word: "diner", meaning: "n.(尤指餐馆的)就餐者", example: "The diner enjoyed his meal at the restaurant. 这位就餐者在餐厅享用他的餐点。" },
    { word: "choke", meaning: "vi.&vt.(使)窒息;(使)哽咽", example: "He choked on a piece of food. 他被一块食物噎住了。" },
    { word: "steak", meaning: "n.牛排;肉排", example: "She ordered a medium-rare steak. 她点了一份五分熟的牛排。" },
    { word: "throat", meaning: "n.咽喉;喉咙", example: "His throat was sore from shouting. 他的喉咙因为喊叫而疼痛。" },
    { word: "desperate", meaning: "a.绝望的;孤注一掷的", example: "He made a desperate attempt to save the business. 他孤注一掷地试图挽救生意。" },
    { word: "slap", meaning: "v.&n(用手)打、拍,拍击声", example: "She gave him a playful slap on the shoulder. 她开玩笑地拍了一下他的肩膀。" },
    { word: "help sb. to one's feet", meaning: "帮助某人站起身来", example: "He helped the old man to his feet after the fall. 老人摔倒后，他扶他站了起来。" },
    { word: "practical", meaning: "a.切实可行的;实际的", example: "Her suggestion was very practical. 她的建议非常实际。" },
    { word: "obstruction", meaning: "n.阻碍;堵塞;阻塞物", example: "The fallen tree caused an obstruction on the road. 倒下的树挡住了道路。" },
    { word: "fist", meaning: "n.拳;拳头", example: "He clenched his fist in anger. 他愤怒地握紧了拳头。" },
    { word: "grab", meaning: "vt.抓住;攫取 n.抓取;抢夺", example: "She grabbed her bag and ran out the door. 她抓起包冲出了门。" },
    { word: "tightly", meaning: "ad.紧紧地;牢固地;紧密地", example: "He held the rope tightly to avoid falling. 他紧紧抓住绳子以防摔倒。" },
    { word: "tight", meaning: "a.牢固的;紧身的 ad.紧紧地", example: "The lid was screwed on tight. 盖子拧得很紧。" },
    { word: "motion", meaning: "n.运动;移动", example: "The motion of the boat made her feel dizzy. 船的晃动让她感到头晕。" },
    { word: "face up", meaning: "面朝上", example: "The card was placed face up on the table. 卡片面朝上放在桌子上。" },
    { word: "face down", meaning: "面朝下", example: "She laid the photo face down. 她把照片面朝下放着。" },
    { word: "justify", meaning: "vt.证明…有理;为…辩护", example: "Can you justify your decision? 你能证明你的决定是正确的吗？" },
    { word: "welfare", meaning: "n.幸福;福祉;安康;福利", example: "The government provides welfare for the needy. 政府为贫困人群提供福利。" },
    { word: "collapse", meaning: "vi.(突然)倒塌;(因病)昏倒", example: "The old building collapsed during the earthquake. 旧建筑在地震中倒塌了。" },
    { word: "manual", meaning: "n.使用手册;说明书a.用手的", example: "He fixed the machine using the manual. 他按照说明书修好了机器。" },
    { word: "sleep in", meaning: "迟起;睡过头;睡懒觉", example: "On weekends, I like to sleep in. 周末我喜欢睡懒觉。" },
    { word: "out of shape", meaning: "健康状况不好", example: "He felt out of shape after months of inactivity. 几个月不运动后，他感觉身体状态不佳。" },
    { word: "foggy", meaning: "a.有雾的", example: "The morning was so foggy that visibility was low. 早晨雾气很重，能见度很低。" },
    { word: "suburb", meaning: "n.郊区;城外", example: "They moved to a quiet suburb. 他们搬到了一个安静的郊区。" },
    { word: "membership", meaning: "n.会员身份;全体会员", example: "She renewed her gym membership. 她续订了健身房的会员资格。" },
    { word: "precise", meaning: "a.准确的;精确的", example: "The measurements need to be precise. 测量必须精确。" },
    { word: "precisely", meaning: "ad.准确地;精确地;的确如此", example: "The meeting started precisely at 9 AM. 会议在上午9点准时开始。" },
    { word: "Christianity", meaning: "n.基督教", example: "Christianity is one of the world's major religions. 基督教是世界主要宗教之一。" },
    { word: "realistic", meaning: "a.现实的;通真的", example: "Her paintings are incredibly realistic. 她的画作非常逼真。" },
    { word: "realism", meaning: "n.逼真;现实主义;务实作风", example: "The novel is praised for its realism. 这部小说因其现实主义风格而受到赞扬。" },
    { word: "realist", meaning: "n.现实主义画家(或作家等)", example: "As a realist, he focused on everyday life. 作为现实主义者，他关注日常生活。" },
    { word: "primitive", meaning: "a.发展水平低的;原始的", example: "The tribe uses primitive tools for hunting. 这个部落使用原始工具狩猎。" },
    { word: "two-dimensional", meaning: "a.二维的", example: "The drawing is a two-dimensional representation. 这幅画是二维的表现形式。" },
    { word: "dimension", meaning: "n.维;规模;范围", example: "The project has many dimensions to consider. 这个项目有许多方面需要考虑。" },
    { word: "in particular", meaning: "尤其;特别", example: "I love all fruits, in particular strawberries. 我喜欢所有水果，尤其是草莓。" },
    { word: "set apart from", meaning: "使与众不同;使突出", example: "Her talent sets her apart from the others. 她的才华使她与众不同。" },
    { word: "humanistic", meaning: "a.人文主义的", example: "The course focuses on humanistic values. 这门课程关注人文主义价值观。" },
    { word: "humanity", meaning: "n.人性;人道;(统称)人类", example: "We must protect the dignity of humanity. 我们必须保护人类的尊严。" },
    { word: "breakthrough", meaning: "n.重大进展;突破", example: "The research led to a major breakthrough. 这项研究取得了重大突破。" },
    { word: "influential", meaning: "a.有很大影响的;有支配力的", example: "He is an influential figure in the industry. 他是行业内有影响力的人物。" },
    { word: "reputation", meaning: "n.名誉;名声", example: "She has a reputation for being honest. 她以诚实著称。" },
    { word: "noble", meaning: "n.贵族成员 a.崇高的;宏伟的", example: "The castle was once home to a noble family. 这座城堡曾是一个贵族家庭的住所。" },
    { word: "rank", meaning: "n.地位;级别;行列 v.分等级", example: "He holds a high rank in the company. 他在公司中职位很高。" },
    { word: "purchase", meaning: "vt.购买;采购 n.购买", example: "She made a large purchase at the store. 她在商店里买了很多东西。" },
    { word: "mythology", meaning: "n.神话;虚幻的想法", example: "Greek mythology is full of fascinating stories. 希腊神话充满了引人入胜的故事。" },
    { word: "client", meaning: "n.委托人;当事人;客户", example: "The lawyer met with his client. 律师与他的委托人会面。" },
    { word: "photography", meaning: "n.照相术;摄影", example: "She has a passion for photography. 她对摄影充满热情。" },
    { word: "emerge", meaning: "vi.&vt.出现;浮现;暴露", example: "The sun emerged from behind the clouds. 太阳从云层后露出来。" },
    { word: "sunrise", meaning: "n.日出", example: "We woke up early to watch the sunrise. 我们早起看日出。" },
    { word: "convey", meaning: "vt.表达;传递(思想/感情等)", example: "Her words conveyed a sense of hope. 她的话传递了一种希望感。" },
    { word: "subjective", meaning: "a.主观的", example: "Art appreciation is highly subjective. 艺术欣赏是非常主观的。" },
    { word: "outer", meaning: "a.外表的;外边的;外围的", example: "The outer layer of the cake was crispy. 蛋糕的外层是酥脆的。" },
    { word: "subsequent", meaning: "a.随后的;后来的;之后的", example: "Subsequent events proved him right. 随后的事件证明他是对的。" },
    { word: "fond", meaning: "a.喜爱", example: "She is fond of classical music. 她喜欢古典音乐。" },
    { word: "be fond of", meaning: "喜爱;喜欢", example: "He is fond of playing chess. 他喜欢下棋。" },
    { word: "fine art", meaning: "美术(尤其绘画和雕塑)", example: "The museum has a collection of fine art. 博物馆收藏了许多美术作品。" },
    { word: "sculpture", meaning: "n.雕像;雕刻品;雕刻术", example: "The sculpture in the park is impressive. 公园里的雕像令人印象深刻。" },
    { word: "sculptor", meaning: "n.雕刻家;雕塑家", example: "The sculptor created a masterpiece. 这位雕塑家创作了一件杰作。" },
    { word: "visual", meaning: "a.视觉的;视力的", example: "The film has stunning visual effects. 这部电影有令人惊叹的视觉效果。" },
    { word: "water lily", meaning: "n.睡莲", example: "The pond was covered with water lilies. 池塘里长满了睡莲。" },
    { word: "pond", meaning: "n.池塘;水池", example: "Children were playing by the pond. 孩子们在池塘边玩耍。" },
    { word: "arched", meaning: "a.拱形的;弓形的", example: "The bridge has an arched design. 这座桥是拱形设计。" },
    { word: "arch", meaning: "v.呈弧形横跨 n.拱;拱门", example: "The cat arched its back. 猫弓起了背。" },
    { word: "investment", meaning: "n.投资额;投资;(时间)投入", example: "The company made a large investment in technology. 公司在技术上投入了大量资金。" },
    { word: "bride", meaning: "n.新娘", example: "The bride looked beautiful in her dress. 新娘穿着婚纱，看起来很美。" },
    { word: "permanent", meaning: "a.永久的;永恒的;长久的", example: "The tattoo is a permanent mark. 纹身是一个永久的标记。" },
    { word: "memorial", meaning: "n.纪念碑;纪念物 a.纪念的", example: "They built a memorial to honor the soldiers. 他们建了一座纪念碑来纪念士兵。" },
    { word: "humble", meaning: "a.谦逊的;虚心的;卑微的", example: "Despite his success, he remained humble. 尽管取得了成功，他仍然很谦逊。" },
    { word: "criticise", meaning: "vi.&vt.批评;指责;评价", example: "She criticised his careless mistake. 她批评了他的粗心错误。" },
    { word: "criticism", meaning: "n.批评;指责;评论", example: "He accepted the criticism gracefully. 他优雅地接受了批评。" },
    { word: "representative", meaning: "a.典型的;代表性的 n.代表", example: "She is a representative of the company. 她是公司的代表。" },
    { word: "ink", meaning: "n.墨水;墨汁;油墨", example: "The pen ran out of ink. 钢笔没墨水了。" },
    { word: "animation", meaning: "n.(电脑)动画制作;动画片", example: "He works in the field of animation. 他从事动画制作工作。" },
    { word: "frame", meaning: "n.画面;框架 vt.镶框", example: "She framed the photo and hung it on the wall. 她把照片装裱起来挂在墙上。" },
    { word: "symphony", meaning: "n.交响乐;交响曲", example: "The orchestra performed a Beethoven symphony. 乐团演奏了一首贝多芬的交响曲。" },
    { word: "decline", meaning: "n.(数量)减少;下降 v.减少", example: "The population of the town is in decline. 这个城镇的人口在减少。" },
    { word: "exhibition", meaning: "n.展览;(技能/感情)表演", example: "The art exhibition attracted many visitors. 艺术展览吸引了许多参观者。" },
    { word: "bronze", meaning: "n.青铜;深红 a.青铜色的", example: "The statue is made of bronze. 这座雕像是青铜制成的。" },
    { word: "ceramic", meaning: "n.陶瓷制品;制陶艺术", example: "She collects ceramic bowls. 她收藏陶瓷碗。" },
    { word: "vase", meaning: "n.花瓶;装饰瓶", example: "She placed the flowers in a vase. 她把花插在花瓶里。" },
    { word: "artistic", meaning: "a.艺术的;艺术家的", example: "She has an artistic temperament. 她有艺术家的气质。" },
    { word: "entry", meaning: "n.加入;进入;参与", example: "The entry fee for the contest is $10. 比赛的报名费是10美元。" },
    { word: "civil", meaning: "a.国民的;民用的;民事的", example: "The case was settled in civil court. 此案在民事法庭得到解决。" },
    { word: "recognition", meaning: "n.承认;认出;赞誉", example: "Her work earned her international recognition. 她的工作为她赢得了国际认可。" },
    { word: "Buddhist", meaning: "a.佛教的 n.佛教徒", example: "The temple is a Buddhist site. 这座寺庙是佛教场所。" },
    { word: "Buddhism", meaning: "n.佛教", example: "Buddhism teaches the path to enlightenment. 佛教教导通往觉悟的道路。" },
    { word: "expansion", meaning: "n.扩张;扩展;扩大", example: "The company plans an expansion into new markets. 公司计划扩展到新市场。" },
    { word: "bring ... to life", meaning: "赋…生命;使…鲜活起来", example: "The actor brought the character to life. 演员将这个角色演活了。" },
    { word: "guarantee", meaning: "vt.保证;确保 n.保证", example: "The product comes with a one-year guarantee. 产品有一年的保修期。" },
    { word: "contemporary", meaning: "a.当代的;现代的 n.同代人", example: "She is a contemporary artist. 她是一位当代艺术家。" },
    { word: "worthy", meaning: "a.值得…的;有价值的", example: "The cause is worthy of support. 这项事业值得支持。" },
    { word: "be worthy of", meaning: "值得", example: "His actions are worthy of praise. 他的行为值得赞扬。" },
    { word: "tobacco", meaning: "n.烟草;烟叶", example: "Tobacco farming is common in this region. 这个地区普遍种植烟草。" },
    { word: "alcohol", meaning: "n.酒;酒精", example: "The drink contains a small amount of alcohol. 这种饮料含有少量酒精。" },
    { word: "abuse", meaning: "n.滥用;虐待 vt.滥用;虐待", example: "Drug abuse is a serious problem. 药物滥用是一个严重的问题。" },
    { word: "physical", meaning: "a.身体的;客观存在的", example: "Regular exercise improves physical health. 定期锻炼有益身体健康。" },
    { word: "dominate", meaning: "vt.&vi.支配;控制;占优势", example: "The team dominated the game. 这支球队在比赛中占据优势。" },
    { word: "repeatedly", meaning: "ad.重复地", example: "He asked the same question repeatedly. 他反复问同一个问题。" },
    { word: "psychology", meaning: "n.心理学;心理;心理影响", example: "She studied psychology in college. " },
    { word: "cue", meaning: "n.提示;暗示 vt.给…暗示", example: "The actor missed his cue to enter the stage. 演员错过了上台的提示。" },
    { word: "in response to", meaning: "回答;答复", example: "She smiled in response to his compliment. 她对他的赞美报以微笑。" },
    { word: "reward", meaning: "n.回报;奖励 vt.奖励;奖赏", example: "Hard work always brings its own reward. 努力总会有回报。" },
    { word: "rely", meaning: "vi.依赖;依靠;信赖", example: "You can rely on me to keep your secret. 你可以相信我会保守你的秘密。" },
    { word: "rely on", meaning: "依赖;依靠;信赖", example: "Children rely on their parents for support. 孩子们依赖父母的支持。" },
    { word: "facilitate", meaning: "vt.促进;促使;使便利", example: "The new software facilitates online collaboration. 新软件促进了在线协作。" },
    { word: "examine", meaning: "vt.(仔细)检查;审查;测验", example: "The doctor will examine your throat tomorrow. 医生明天会检查你的喉咙。" },
    { word: "negative", meaning: "a.消极的;有害的;否定的", example: "His negative attitude affected the whole team. 他的消极态度影响了整个团队。" },
    { word: "escalator", meaning: "n.自动扶梯;滚梯", example: "Please hold the handrail while riding the escalator. 乘坐自动扶梯时请握紧扶手。" },
    { word: "straight away", meaning: "立即;马上", example: "I'll call him straight away. 我马上给他打电话。" },
    { word: "pessimistic", meaning: "a.悲观的;悲观主义的", example: "Don't be so pessimistic about the future. 不要对未来如此悲观。" },
    { word: "discipline", meaning: "n.自制力;纪律 vt.自我控制", example: "Daily exercise requires great discipline. 每日锻炼需要很强的自制力。" },
    { word: "pill", meaning: "n.药丸;药片", example: "She took a pill to relieve her headache. 她吃了一片药缓解头痛。" },
    { word: "delete", meaning: "v.删去;删除", example: "Please delete the unnecessary files. 请删除不必要的文件。" },
    { word: "decide on", meaning: "决定;选定", example: "Have you decided on a date for the party? 你决定好派对日期了吗？" },
    { word: "make up one's mind", meaning: "下定决心", example: "He finally made up his mind to study abroad. 他终于下定决心出国留学。" },
    { word: "compose", meaning: "vt.&vi.组成;作曲;撰写", example: "Mozart composed this symphony at age eight. 莫扎特八岁时创作了这首交响曲。" },
    { word: "be composed of", meaning: "由…组成(或构成)的", example: "Water is composed of hydrogen and oxygen. 水由氢和氧组成。" },
    { word: "surgeon", meaning: "n.外科医生", example: "The surgeon performed a successful heart operation. 外科医生成功完成了一台心脏手术。" },
    { word: "surgery", meaning: "n.外科手术;外科学", example: "He underwent surgery to remove the tumor. 他接受了肿瘤切除手术。" },
    { word: "liberation", meaning: "n.解放;摆脱", example: "The liberation of the city marked the end of the war. 城市的解放标志着战争的结束。" },
    { word: "shave", meaning: "vi,vt.&n.剃(须发);刮脸", example: "He shaves every morning before work. 他每天上班前都会刮胡子。" },
    { word: "shave off", meaning: "剃掉;刮去", example: "He decided to shave off his beard. 他决定剃掉胡子。" },
    { word: "beard", meaning: "n.胡须;络腮胡子", example: "His beard grew thick during the winter. 他的胡子在冬天长得很浓密。" },
    { word: "disturb", meaning: "vt.打扰;搅乱;使烦恼", example: "Please don't disturb him while he's working. 他工作时请不要打扰他。" },
    { word: "cigarette", meaning: "n.香烟;卷烟", example: "Smoking cigarettes is harmful to health. 吸烟有害健康。" },
    { word: "specialist", meaning: "n.专科医生;专家", example: "She is a specialist in ancient Greek history. 她是古希腊历史专家。" },
    { word: "consultant", meaning: "n.顾问;高级顾问医师", example: "The company hired a consultant to improve efficiency. 公司聘请了一位顾问来提高效率。" },
    { word: "drug", meaning: "n.毒品;药物", example: "This drug can effectively relieve pain. 这种药物能有效缓解疼痛。" },
    { word: "skip", meaning: "v.跳过;不参加 vi.跳绳", example: "She skips breakfast to save time. 为了节省时间，她不吃早餐。" },
    { word: "dizzy", meaning: "a.头晕目眩的", example: "I felt dizzy after spinning around. 转圈后我感到头晕目眩。" },
    { word: "flu", meaning: "n.流感", example: "He caught the flu and had to stay in bed. 他得了流感，不得不卧床休息。" },
    { word: "stimulate", meaning: "vt.激发;促进;刺激", example: "Coffee can stimulate the brain. 咖啡可以刺激大脑。" },
    { word: "dentist", meaning: "n.牙科医生", example: "You should visit the dentist twice a year. 你应该每年看两次牙医。" },
    { word: "sugary", meaning: "a.含糖的;甜的", example: "Avoid sugary drinks to protect your teeth. 为了保护牙齿，避免饮用含糖饮料。" },
    { word: "nut", meaning: "n.坚果", example: "Squirrels love to eat nuts. 松鼠喜欢吃坚果。" },
    { word: "skateboard", meaning: "n.滑板 vi.滑滑板", example: "He hurt his knee while skateboarding. 他滑滑板时伤了膝盖。" },
    { word: "dynamic", meaning: "a.充满活力的;精力充沛的", example: "She has a dynamic personality. 她性格充满活力。" },
    { word: "stressed out", meaning: "焦虑不安;疲惫不堪", example: "He was stressed out before the exam. 考试前他焦虑不安。" },
    { word: "worn out", meaning: "筋疲力尽的;疲惫的", example: "After the marathon, I was completely worn out. 马拉松比赛后，我筋疲力尽。" },
    { word: "bowling", meaning: "n.保龄球运动", example: "We went bowling last weekend. 我们上周末去打保龄球了。" },
    { word: "comedy", meaning: "n.喜剧;喜剧片;滑稽节目", example: "This comedy made everyone laugh. 这部喜剧让所有人都笑了。" },
    { word: "monthly", meaning: "ad.每月;每月一次的 n.月刊", example: "The magazine is published monthly. 这本杂志每月出版一次。" },
    { word: "enhance", meaning: "vt.提高;增强;增进", example: "Exercise can enhance your health. 锻炼可以增强你的健康。" },
    { word: "refresh", meaning: "v.使恢复精力;使凉爽;刷新", example: "A cold shower will refresh you. 冷水淋浴会让你恢复精力。" },
    { word: "absorb", meaning: "vt.吸引全部注意力;吸收", example: "The sponge absorbed all the water. 海绵吸收了所有的水。" },
    { word: "graph", meaning: "n.图;图表;曲线图", example: "The graph shows a steady increase. 图表显示稳定增长。" },
    { word: "emission", meaning: "n.排放物;散发物;排放", example: "Car emissions pollute the air. 汽车排放物污染空气。" },
    { word: "melt", meaning: "vi.&vt.(使)融化;熔化;软化", example: "The ice cream melted in the sun. 冰淇淋在阳光下融化了。" },
    { word: "starve", meaning: "vi.&vt.(使)挨饿;饿死", example: "Many people starved during the famine. 许多人在饥荒中挨饿。" },
    { word: "seal", meaning: "n.海豹", example: "We saw a seal at the aquarium. 我们在水族馆看到了一只海豹。" },
    { word: "ecology", meaning: "n.生态;生态学", example: "We must protect the ecology of the forest. 我们必须保护森林生态。" },
    { word: "release", meaning: "vt.&n.排放;释放;发布", example: "The company will release a new product next month. 公司下个月将发布新产品。" },
    { word: "methane", meaning: "n.甲烷;沼气", example: "Methane is a potent greenhouse gas. 甲烷是一种强效温室气体。" },
    { word: "carbon", meaning: "n.碳", example: "Diamonds are made of pure carbon. 钻石由纯碳构成。" },
    { word: "dioxide", meaning: "n.二氧化物", example: "Carbon dioxide is essential for plant growth. 二氧化碳对植物生长至关重要。" },
    { word: "carbon dioxide", meaning: "二氧化碳", example: "Plants absorb carbon dioxide and release oxygen. 植物吸收二氧化碳并释放氧气。" },
    { word: "habitable", meaning: "a.适合居住的", example: "Scientists are searching for habitable planets. 科学家正在寻找适合居住的行星。" },
    { word: "sustain", meaning: "vt.维持;遭受;承受住", example: "The pillars sustain the weight of the roof. 柱子承受着屋顶的重量。" },
    { word: "sustainable", meaning: "a.可持续的;合理利用的", example: "We need sustainable energy sources. 我们需要可持续的能源。" },
    { word: "fossil", meaning: "n.化石", example: "This fossil is millions of years old. 这块化石有数百万年的历史。" },
    { word: "fuel", meaning: "n.燃料;刺激性言行", example: "Wood was used as fuel in ancient times. 古代用木头作燃料。" },
    { word: "fossil fuel", meaning: "化石燃料(如煤或石油)", example: "Burning fossil fuels causes pollution. 燃烧化石燃料会造成污染。" },
    { word: "comprehensive", meaning: "a.全部的;所有的;详尽的", example: "The report provides a comprehensive analysis. 报告提供了全面的分析。" },
    { word: "worldwide", meaning: "ad.遍全球地 a.世界各地的", example: "This product is sold worldwide. 这种产品在全球销售。" },
    { word: "trend", meaning: "n.趋势;趋向;动向", example: "Online shopping is a growing trend. 网购是一种增长趋势。" },
    { word: "frequently", meaning: "ad.频繁地;经常", example: "She frequently visits her grandparents. 她经常去看望祖父母。" },
    { word: "broadcast", meaning: "v.播送;广播 n.广播节目", example: "The news was broadcast live. 新闻是现场直播的。" },
    { word: "policy", meaning: "n.政策;方针;原则", example: "The company has a strict no-smoking policy. 公司有严格的禁烟政策。" },
    { word: "footprint", meaning: "n.足迹;(某物所占)空间量", example: "We found footprints in the snow. 我们在雪地里发现了足迹。" },
    { word: "restrict", meaning: "vt.限制;限定;束缚", example: "The law restricts smoking in public places. 法律限制在公共场所吸烟。" },
    { word: "restriction", meaning: "n.限制规定;限制法规;约束", example: "There are no restrictions on parking here. 这里停车没有限制。" },
    { word: "seize", meaning: "vt.抓住;夺取;控制", example: "The police seized the stolen goods. 警方查获了赃物。" },
    { word: "basin", meaning: "n.流域;盆地;盆", example: "The Amazon basin is rich in biodiversity. 亚马逊流域生物多样性丰富。" },
    { word: "penguin", meaning: "n.企鹅", example: "Penguins live in the Antarctic. 企鹅生活在南极。" },
    { word: "reform", meaning: "v.改革;改正 n.改革;变革", example: "The government implemented education reforms. 政府实施了教育改革。" },
    { word: "undergo", meaning: "v.经历;经受(变化/不快等)", example: "The patient will undergo surgery tomorrow. 病人明天将接受手术。" },
    { word: "implement", meaning: "vt.使生效;贯彻;执行", example: "The new rules will be implemented next month. 新规则将于下月实施。" },
    { word: "harmonious", meaning: "a.和谐的", example: "They live in a harmonious community. 他们生活在一个和谐的社区。" },
    { word: "moderate", meaning: "a.适度的;中等的 v.缓和", example: "He has a moderate income. 他有中等收入。" },
    { word: "submit", meaning: "vt.&vi.提交;呈递;屈服", example: "Please submit your report by Friday. 请在周五前提交报告。" },
    { word: "annual", meaning: "a.每年的;一年的 n.年刊", example: "The company holds an annual meeting in December. 公司每年十二月召开年会。" },
    { word: "tropical", meaning: "a.热带的;来自热带的", example: "Bananas grow in tropical climates. 香蕉生长在热带气候中。" },
    { word: "chaos", meaning: "n.混乱;杂乱;紊乱", example: "The storm caused chaos in the city. 暴风雨在城市中造成了混乱。" },
    { word: "on behalf of", meaning: "代表(代替)某人", example: "I'm speaking on behalf of the team. 我代表团队发言。" },
    { word: "nuclear", meaning: "a.原子能的;核能的", example: "Nuclear energy is a controversial topic. 核能是一个有争议的话题。" },
    { word: "sensitive", meaning: "a.敏感的;善解人意的", example: "She is very sensitive to others' feelings. 她对别人的感受非常敏感。" },
    { word: "jungle", meaning: "n.(热带)丛林;密林", example: "The jungle is full of wild animals. 丛林里有很多野生动物。" },
    { word: "smog", meaning: "n.烟雾(烟与雾混合污染物)", example: "The city was covered in thick smog. 城市被厚厚的烟雾笼罩。" },
    { word: "originate", meaning: "vi.&vt.起源;发源;创立", example: "This tradition originated in ancient times. 这一传统起源于古代。" },
    { word: "volume", meaning: "n.量;体积;(成套书中)一卷", example: "The library has a large volume of books. 图书馆有大量藏书。" },
    { word: "garbage", meaning: "n.垃圾;废物", example: "Please take out the garbage. 请把垃圾拿出去。" },
    { word: "enterprise", meaning: "n.公司;企业;事业", example: "He started his own enterprise last year. 他去年创办了自己的企业。" },
    { word: "restore", meaning: "vt.恢复;使复原;修复", example: "They restored the old castle. 他们修复了古堡。" },
    { word: "conservation", meaning: "n.对(环境/文物)保护;保持", example: "Wildlife conservation is important. 野生动物保护很重要。" },
    { word: "dozen", meaning: "n.(一)打;十二个", example: "I bought a dozen eggs. 我买了一打鸡蛋。" },
    { word: "dozens of", meaning: "许多;很多", example: "Dozens of people attended the meeting. 许多人参加了会议。" },
    { word: "regulation", meaning: "n.章程;规章制度", example: "Safety regulations must be followed. 必须遵守安全规章。" },
    { word: "disposal", meaning: "n.去掉;清除;处理", example: "Waste disposal is an environmental issue. 废物处理是一个环境问题。" },
    { word: "inspection", meaning: "n.检查;查看;视察", example: "The car passed the inspection. 汽车通过了检查。" },
    { word: "fine", meaning: "vt.对…处以罚款", example: "He was fined for speeding. 他因超速被罚款。" },
    { word: "campaign", meaning: "n.运动;战役 v.参加运动", example: "The election campaign was intense. 选举运动很激烈。" },
    { word: "waterway", meaning: "n.水道;航道", example: "The canal is an important waterway. 这条运河是重要的航道。" },
    { word: "tolerate", meaning: "vt.忍受;包容;容许", example: "I can't tolerate his rudeness. 我无法忍受他的无礼。" },
    { word: "agenda", meaning: "n.议程表;议事日程", example: "The first item on the agenda is the budget. 议程上的第一项是预算。" },
    { word: "adversity", meaning: "n.困境;逆境", example: "He remained strong in the face of adversity. 面对逆境，他依然坚强。" },
    { word: "wage", meaning: "n.工资", example: "The workers demanded higher wages. 工人们要求加薪。" },
    { word: "bitter", meaning: "a.严寒的;激烈而不愉快的", example: "The bitter cold made everyone shiver. 严寒让每个人都发抖。" },
    { word: "expedition", meaning: "n.探险;远征;探险队", example: "They went on an expedition to the Arctic. 他们去北极探险。" },
    { word: "endurance", meaning: "n.忍耐力;耐久力", example: "Marathon runners need great endurance. 马拉松运动员需要很强的耐力。" },
    { word: "vigour", meaning: "n.精力;力量;活动", example: "He works with great vigour. 他工作精力充沛。" },
    { word: "turn sb. down", meaning: "拒绝(某人)", example: "She turned down his invitation. 她拒绝了他的邀请。" },
    { word: "qualified", meaning: "a.符合资格;具…知识/技能", example: "She is highly qualified for the job. 她完全有资格胜任这份工作。" },
    { word: "enthusiastic", meaning: "a.热情的;热心的", example: "The students were enthusiastic about the project. 学生们对这个项目很热情。" },
    { word: "aboard", meaning: "ad.&prep.上(船/飞机等)", example: "All passengers must be aboard by 8 PM. 所有乘客必须在晚上8点前登机。" },
    { word: "cupboard", meaning: "n.橱柜;壁橱;衣柜", example: "The plates are in the cupboard. 盘子在橱柜里。" },
    { word: "assign", meaning: "vt.分派;布置;分配", example: "The teacher assigned homework. 老师布置了家庭作业。" },
    { word: "steward", meaning: "n.(轮船/飞机/火车)乘务员", example: "The steward served drinks to the passengers. 乘务员为乘客提供饮料。" },
    { word: "envy", meaning: "n.&vt.羡慕;妒忌", example: "I envy your ability to stay calm. 我羡慕你能保持冷静。" },
    { word: "crush", meaning: "vt.毁坏;压坏 n.拥挤的人群", example: "Don't crush the flowers. 不要压坏花朵。" },
    { word: "sink", meaning: "vi.沉没;下沉 vt.使下沉", example: "The ship sank during the storm. 船在暴风雨中沉没了。" },
    { word: "abandon", meaning: "vt.舍弃;抛弃;放弃", example: "They had to abandon the sinking ship. 他们不得不弃船。" },
    { word: "stove", meaning: "n.炉具;厨房灶具", example: "She cooked soup on the stove. 她在炉子上煮汤。" },
    { word: "blanket", meaning: "n.毯子", example: "He wrapped himself in a warm blanket. 他裹着一条温暖的毯子。" },
    { word: "belongings", meaning: "n.[pl.]财物;动产", example: "Please take care of your belongings. 请保管好你的财物。" },
    { word: "banjo", meaning: "n.班卓琴(乐器)", example: "He played the banjo at the concert. 他在音乐会上演奏了班卓琴。" },
    { word: "miserable", meaning: "a.痛苦的;令人难受的", example: "The cold weather made everyone miserable. 寒冷的天气让每个人都难受。" },
    { word: "voyage", meaning: "n.&vi.航海;航行", example: "The voyage across the ocean took two months. 横渡大洋的航行花了两个月。" },
    { word: "navy", meaning: "n.海军;海军部队", example: "He served in the navy for ten years. 他在海军服役了十年。" },
    { word: "decent", meaning: "a.相当不错的;正派的", example: "He found a decent job after graduation. 毕业后他找到了一份不错的工作。" },
    { word: "cosy", meaning: "a.温馨的;舒适的", example: "The room was small but cosy. 房间虽小但很舒适。" },
    { word: "selfish", meaning: "a.自私的", example: "It's selfish to only think about yourself. 只考虑自己是自私的。" },
    { word: "good-tempered", meaning: "a.脾气好的", example: "She is always good-tempered. 她总是脾气很好。" },
    { word: "bad-tempered", meaning: "a.脾气坏的", example: "The boss is often bad-tempered. 老板经常脾气不好。" },
    { word: "genuine", meaning: "a.真正的;真诚的;可信赖的", example: "She showed genuine concern. 她表现出真诚的关心。" },
    { word: "perseverance", meaning: "n.毅力;韧性;不屈不挠精神", example: "Success requires perseverance. 成功需要毅力。" },
    { word: "persevere", meaning: "vi.坚持;孜孜以求", example: "Despite difficulties, he persevered. 尽管困难重重，他仍坚持。" },
    { word: "resolve", meaning: "v.决定;决心 n.决心", example: "She resolved to study harder. 她决心更加努力学习。" },
    { word: "resolution", meaning: "n.决议;解决;坚定", example: "The UN passed a new resolution. 联合国通过了一项新决议。" },
    { word: "crew", meaning: "n.(轮船/飞机)全体工作人员", example: "The crew prepared for takeoff. 机组人员准备起飞。" },
    { word: "cruel", meaning: "a.残酷的;残忍的;冷酷的", example: "It's cruel to treat animals badly. 虐待动物是残忍的。" },
    { word: "thorough", meaning: "a.深入的;彻底的;细致的", example: "The doctor gave me a thorough examination. 医生给我做了彻底检查。" },
    { word: "furniture", meaning: "n.家具", example: "We bought new furniture for the living room. 我们为客厅买了新家具。" },
    { word: "unfortunately", meaning: "ad.不幸地;遗憾地", example: "Unfortunately, the concert was canceled. 不幸的是，音乐会被取消了。" },
    { word: "fortunately", meaning: "ad.幸运地", example: "Fortunately, no one was hurt. 幸运的是，没有人受伤。" },
    { word: "bark", meaning: "vi.&n.(狗)吠叫;吠叫声", example: "The dog barked at the stranger. 狗对陌生人吠叫。" },
    { word: "rugby", meaning: "n.橄榄球运动", example: "He plays rugby for the school team. 他为校队打橄榄球。" },
    { word: "bat", meaning: "n.球拍;蝙蝠 v.用球板击球", example: "He hit the ball with the bat. 他用球拍击球。" },
    { word: "damp", meaning: "a.潮湿的;湿气重的", example: "The clothes felt damp after the rain. 雨后衣服感觉潮湿。" },
    { word: "recreation", meaning: "n.娱乐;消遣;游戏", example: "Reading is my favorite recreation. 阅读是我最喜欢的消遣。" },
    { word: "guidance", meaning: "n.指导;引导;导航", example: "Teachers provide guidance to students. 老师为学生提供指导。" },
    { word: "nephew", meaning: "n.侄子;外甥", example: "My nephew is five years old. 我侄子五岁了。" },
    { word: "advertising", meaning: "n.广告活动;广告业", example: "She works in advertising. 她在广告业工作。" },
    { word: "advertise", meaning: "vt.&vi.公布;宣传;做广告", example: "The company advertised its new product. 公司为新产品做广告。" },
    { word: "corporate", meaning: "a.公司的;法人的;社团的", example: "He works in corporate finance. 他在公司财务部门工作。" },
    { word: "rough", meaning: "a.汹涌的;粗糙的;粗略的", example: "The sea was rough during the storm. 暴风雨期间海面汹涌。" },
    { word: "navigator", meaning: "n.领航员;(飞机/船)航行者", example: "The navigator plotted the course. 领航员规划了航线。" },
    { word: "loyal", meaning: "a.忠诚的;忠实的", example: "Dogs are loyal to their owners. 狗对主人忠诚。" },
    { word: "motor", meaning: "n.发动机;马达 a.有引擎的", example: "The motor stopped working. 马达停止工作了。" },
    { word: "candidate", meaning: "n.候选人;应试者", example: "There are three candidates for the position. 这个职位有三名候选人。" },
    { word: "make fire", meaning: "生火", example: "They made fire to keep warm. 他们生火取暖。" },
    { word: "give off", meaning: "放出(热/光/气味/气体)", example: "The flowers give off a sweet fragrance. 花朵散发出甜美的香气。" },
    { word: "episode", meaning: "n.(人生)一段经历;小说片段", example: "This is the final episode of the series. 这是该系列的最后一集。" },
    { word: "commitment", meaning: "n.承诺;保证;奉献", example: "She has a strong commitment to her work. 她对工作有强烈的奉献精神。" },
    { word: "motive", meaning: "n.动机;原因;目的", example: "The police are investigating the motive. 警方正在调查动机。" },
    { word: "Confucianism", meaning: "n.孔子学说;儒家(学说)", example: "Confucianism has influenced Chinese culture deeply. 儒家学说深深影响了中国文化。" },
    { word: "drama", meaning: "n.戏;剧;戏剧艺术", example: "She studies drama at university. 她在大学学习戏剧。" },
    { word: "sorrow", meaning: "n.悲伤;悲痛 vi.感到悲伤", example: "He felt deep sorrow at the loss. 他对失去感到深深的悲伤。" },
    { word: "imagery", meaning: "n.形象的描述;意象;像", example: "The poem is rich in imagery. 这首诗意象丰富。" },
    { word: "literary", meaning: "a.文学的;爱好文学的", example: "He has a literary style of writing. 他的写作具有文学风格。" },
    { word: "rhyme", meaning: "n.押韵词;押韵诗 v.使押韵", example: "The poem doesn't rhyme. 这首诗不押韵。" },
    { word: "rhythm", meaning: "n.节奏;韵律;规律", example: "The music has a strong rhythm. 音乐有强烈的节奏。" },
    { word: "nursery", meaning: "a.幼儿教育的 n.托儿所", example: "The child goes to nursery every morning. 孩子每天早上上托儿所。" },
    { word: "nursery rhyme", meaning: "童谣;儿歌", example: "Children love singing nursery rhymes. 孩子们喜欢唱童谣。" },
    { word: "folk", meaning: "a.民间的;民俗的", example: "She enjoys folk music. 她喜欢民间音乐。" },
    { word: "diamond", meaning: "n.钻石;金刚石;菱形", example: "She wore a diamond ring. 她戴着一枚钻石戒指。" },
    { word: "brass", meaning: "n.黄铜;黄铜制品;铜管乐器", example: "The doorknob is made of brass. 门把手是黄铜制的。" },
    { word: "billy goat", meaning: "n.公山羊", example: "The billy goat butted the fence. 公山羊用角顶篱笆。" },
    { word: "bull", meaning: "n.公牛", example: "The bull charged at the matador. 公牛冲向斗牛士。" },
    { word: "recite", meaning: "vt.背诵;吟诵;列举", example: "She recited a poem at the assembly. 她在集会上背诵了一首诗。" },
    { word: "bee", meaning: "n.蜜蜂", example: "Bees collect nectar from flowers. 蜜蜂从花朵中采集花蜜。" },
    { word: "dewdrop", meaning: "n.露珠;水珠", example: "Dewdrops glistened on the grass. 露珠在草地上闪闪发光。" },
    { word: "dawn", meaning: "n.黎明;开端;萌芽", example: "We got up at dawn. 我们黎明时分起床。" },
    { word: "clover", meaning: "n.三叶草", example: "A four-leaf clover is considered lucky. 四叶草被认为是幸运的。" },
    { word: "butterfly", meaning: "n.蝴蝶", example: "A butterfly landed on the flower. 一只蝴蝶落在花上。" },
    { word: "lawn", meaning: "n.草坪,草地", example: "He mowed the lawn yesterday. 他昨天修剪了草坪。" },
    { word: "amateur", meaning: "n.业余爱好者 a.业余的", example: "He is an amateur photographer. 他是业余摄影师。" },
    { word: "cinquain", meaning: "n.五行诗", example: "She wrote a cinquain for class. 她为课堂写了一首五行诗。" },
    { word: "be made up of ...", meaning: "组成(构成)", example: "The committee is made up of experts. 委员会由专家组成。" },
    { word: "mood", meaning: "n.情绪;心情;语气", example: "He's in a bad mood today. 他今天心情不好。" },
    { word: "tease", meaning: "v.取笑(某人);揶揄;逗弄", example: "Don't tease your little brother. 不要取笑你弟弟。" },
    { word: "haiku", meaning: "n.俳句", example: "He composed a haiku about autumn. 他写了一首关于秋天的俳句。" },
    { word: "syllable", meaning: "n.音节", example: "The word 'water' has two syllables. “water”这个词有两个音节。" },
    { word: "format", meaning: "n.格式;总体安排 vt.格式化", example: "The document has a standard format. 文件有标准格式。" },
    { word: "respectively", meaning: "ad.分别;各自;依次为", example: "Tom and Jerry are 10 and 8 years old, respectively. 汤姆和杰瑞分别是10岁和8岁。" },
    { word: "respective", meaning: "a.分别的;各自的", example: "They went to their respective rooms. 他们去了各自的房间。" },
    { word: "blossom", meaning: "n.花朵;花簇", example: "Cherry trees are in blossom. 樱花树开花了。" },
    { word: "delicate", meaning: "a.精美的;精致的;脆弱的", example: "Handle the vase with care—it's very delicate. 小心拿花瓶，它很精致。" },
    { word: "await", meaning: "vt.等候;期待;将发生在", example: "We await your reply. 我们等待您的回复。" },
    { word: "revolve", meaning: "vi.旋转;环绕;转动", example: "The Earth revolves around the Sun. 地球绕太阳旋转。" },
    { word: "utter", meaning: "vt.出声;说;讲 a.完全的", example: "He didn't utter a word. 他一句话也没说。" },
    { word: "comprehension", meaning: "n.理解力;领悟力;理解练习", example: "The test measures reading comprehension. 测试测量阅读理解能力。" },
    { word: "shelf", meaning: "n.架子;搁板", example: "Put the book back on the shelf. 把书放回架子上。" },
    { word: "core", meaning: "n.核心;精髓;(水果的)核儿", example: "The core of the problem is lack of communication. 问题的核心是缺乏沟通。" },
    { word: "cherry", meaning: "n.樱桃;樱桃树 a.樱桃色的", example: "She loves cherry pie. 她喜欢樱桃派。" },
    { word: "cherry blossom", meaning: "樱花", example: "We went to see the cherry blossoms. 我们去看樱花了。" },
    { word: "blank", meaning: "a.空白的;无图画 n.空白", example: "Please fill in the blank spaces. 请填写空白处。" },
    { word: "verse", meaning: "n.诗;韵文;诗节", example: "He quoted a verse from the Bible. 他引用了《圣经》中的一节。" },
    { word: "civilian", meaning: "n.平民;老百姓", example: "The attack killed many civilians. 袭击造成许多平民死亡。" },
    { word: "prose", meaning: "n.散文", example: "She writes both poetry and prose. 她既写诗也写散文。" },
    { word: "sympathetic", meaning: "a.同情的;有同情心的", example: "She was sympathetic to his troubles. 她对他的困境表示同情。" },
    { word: "sympathy", meaning: "n.同情;赞同", example: "I have no sympathy for lazy people. 我对懒人没有同情。" },
    { word: "version", meaning: "n.版本;(不同角度的)说法", example: "The latest version of the software includes many new features. 该软件的最新版本包含许多新功能。" },
    { word: "innocence", meaning: "n.天真;单纯;无罪", example: "The child's innocence was evident in her curious questions. 孩子的好奇问题显示出她的天真无邪。" },
    { word: "innocent", meaning: "a.天真无邪的;无辜的", example: "He was proven innocent after the trial. 审判后他被证明是无辜的。" },
    { word: "era", meaning: "n.时代;年代;纪元", example: "The invention marked the beginning of a new era. 这项发明标志着一个新时代的开始。" },
    { word: "correspondence", meaning: "n.来往信件;通信联系", example: "She kept all her correspondence in a special folder. 她将所有来往信件保存在一个专门的文件夹中。" },
    { word: "correspond", meaning: "vi.相一致;符合;相当于", example: "His actions do not correspond with his words. 他的言行不一致。" },
    { word: "sow", meaning: "vt.&vi.播种;种", example: "Farmers sow seeds in the spring. 农民们在春天播种。" },
    { word: "seed", meaning: "n.种子;起源;萌芽", example: "The seed grew into a beautiful flower. 种子长成了一朵美丽的花。" },
    { word: "dominant", meaning: "a.首要的;占支配地位的", example: "The dominant team won the match easily. 占优势的球队轻松赢得了比赛。" },
    { word: "sonnet", meaning: "n.十四行诗", example: "Shakespeare wrote many famous sonnets. 莎士比亚写了许多著名的十四行诗。" },
    { word: "deadline", meaning: "n.最后期限;截止日期", example: "We must finish the project before the deadline. 我们必须在截止日期前完成项目。" },
    { word: "contest", meaning: "n.比赛;竞赛 vt.争取赢得", example: "She won first prize in the singing contest. 她在歌唱比赛中获得了一等奖。" },
    { word: "polish", meaning: "vt.修改;润色 n.上光剂", example: "He spent hours polishing his speech. 他花了几个小时润色他的演讲。" },
    { word: "string", meaning: "n.细绳;线 vt.悬挂;系", example: "She tied the package with a piece of string. 她用一根细绳把包裹系好。" },
    { word: "wherever", meaning: "conj.在任何地方 ad.在哪里", example: "Wherever you go, I will follow. 无论你去哪里，我都会跟随。" },
    { word: "barren", meaning: "a.贫瘠的;不结果实的", example: "The barren land could not support crops. 贫瘠的土地无法种植庄稼。" },
    { word: "grief", meaning: "n.悲伤;悲痛;伤心事", example: "She felt deep grief after her loss. 失去后她感到深深的悲伤。" },
    { word: "complicated", meaning: "a.复杂的;难懂的", example: "The instructions were too complicated to follow. 说明书太复杂，难以理解。" },
    { word: "variation", meaning: "n.变化;变体;变奏曲", example: "There are many variations of this recipe. 这个食谱有许多变体。" },
    { word: "racial", meaning: "a.种族的;人种的", example: "Racial equality is an important goal for society. 种族平等是社会的重要目标。" },
    { word: "prejudice", meaning: "n.偏见;成见 vt.使怀有偏见", example: "We should avoid making decisions based on prejudice. 我们应该避免基于偏见做决定。" },
    { word: "fiction", meaning: "n.小说;虚构的事", example: "He enjoys reading science fiction in his free time. 他喜欢在空闲时间读科幻小说。" },
    { word: "science fiction", meaning: "[abbr.SF]科幻小说/影片等", example: "Science fiction often explores futuristic technologies. 科幻小说常常探索未来科技。" },
    { word: "test out", meaning: "检验;测试", example: "We need to test out the new equipment before using it. 我们需要在使用前测试新设备。" },
    { word: "bonus", meaning: "n.意外收获;奖金;红利", example: "Employees received a year-end bonus for their hard work. 员工们因努力工作获得了年终奖金。" },
    { word: "more like", meaning: "更像是;更接近", example: "The weather is more like spring than winter today. 今天的天气更像是春天而不是冬天。" },
    { word: "ridiculous", meaning: "a.愚蠢的;荒谬的;荒唐的", example: "His idea was so ridiculous that no one took it seriously. 他的想法太荒谬了，没人当真。" },
    { word: "integrity", meaning: "n.诚实正直;完整;完好", example: "She is known for her integrity and strong moral principles. 她以诚实正直和强烈的道德原则闻名。" },
    { word: "dignity", meaning: "n.庄重;庄严;尊严", example: "He faced the challenge with great dignity. 他以极大的尊严面对挑战。" },
    { word: "salary", meaning: "n.薪水;薪金", example: "Her salary increased after the promotion. 升职后她的薪水增加了。" },
    { word: "absurd", meaning: "a.荒谬的;荒唐的", example: "The idea that the earth is flat is completely absurd. 地球是平的这一想法完全荒谬。" },
    { word: "appointment", meaning: "n.预约;约会;委任", example: "I have an appointment with the dentist at 3 PM. 我下午3点约了牙医。" },
    { word: "nail", meaning: "n.指甲;趾甲 vt.(用钉)钉牢", example: "She painted her nails bright red. 她把指甲涂成了亮红色。" },
    { word: "saleswoman", meaning: "n.女售货员;女推销员", example: "The saleswoman helped me find the perfect dress. 女售货员帮我找到了完美的裙子。" },
    { word: "guilty", meaning: "a.内疚的;有罪的;有过失的", example: "He felt guilty for forgetting his friend's birthday. 他因为忘记朋友的生日而感到内疚。" },
    { word: "suspend", meaning: "vt.悬;挂;暂停;暂缓", example: "The school decided to suspend the student for breaking the rules. 学校决定暂停违反规定的学生的学籍。" },
    { word: "ladder", meaning: "n.梯子;阶梯", example: "He climbed the ladder to fix the roof. 他爬上梯子去修理屋顶。" },
    { word: "dismiss", meaning: "vt.让(某人)离开;解散;解雇", example: "The manager had to dismiss the employee for repeated tardiness. 经理因员工多次迟到而解雇了他。" },
    { word: "declare", meaning: "vt.表明;宣称;公布", example: "The president declared a state of emergency. 总统宣布进入紧急状态。" },
    { word: "whereas", meaning: "conj.然而;但是;尽管", example: "She loves spicy food, whereas her brother prefers mild flavors. 她喜欢辛辣食物，而她弟弟更喜欢清淡口味。" },
    { word: "rumour", meaning: "n.谣言;传闻", example: "The rumour about their breakup spread quickly. 关于他们分手的谣言迅速传开。" },
    { word: "presume", meaning: "vt.&vi.假设;假定", example: "We can presume that he will attend the meeting. 我们可以假设他会参加会议。" },
    { word: "fare", meaning: "n.车费;船费;飞机票价", example: "The bus fare has increased this year. 今年的公交车费上涨了。" },
    { word: "weekly", meaning: "a.每周的 n.周刊", example: "She reads the weekly magazine every Sunday. 她每周日都会读这本周刊。" },
    { word: "on a ... basis", meaning: "根据;以…的方式(基准)", example: "Employees are paid on a monthly basis. 员工按月领取工资。" },
    { word: "calculate", meaning: "vt.计算;核算;预测", example: "Scientists can calculate the distance between planets. 科学家可以计算行星之间的距离。" },
    { word: "chairwoman", meaning: "n.女主席;女董事长;女委员长", example: "The chairwoman led the meeting with great efficiency. 女主席高效地主持了会议。" },
    { word: "gramme", meaning: "n.克(重量单位)", example: "The recipe requires 200 grammes of flour. 这个食谱需要200克面粉。" },
    { word: "flour", meaning: "n.面粉;(谷物磨成的)粉", example: "She sifted the flour before adding it to the mixture. 她在加入混合物前筛了面粉。" },
    { word: "venue", meaning: "n.活动场地(音乐厅/会场等)", example: "The concert venue was packed with excited fans. 音乐会场地挤满了兴奋的粉丝。" },
    { word: "salesman", meaning: "n.售货员;推销员", example: "The salesman demonstrated how the product works. 推销员演示了产品的使用方法。" },
    { word: "alien", meaning: "n.外星人;外国人 a. 陌生的", example: "The movie is about an alien visiting Earth. 这部电影讲述了一个外星人访问地球的故事。" },
    { word: "pros and cons", meaning: "事物的利与弊;支持与反对", example: "We discussed the pros and cons of the new policy. 我们讨论了新政策的利弊。" },
    { word: "blurred", meaning: "a.模糊不清的;难以区分的", example: "The photo was blurred because the camera moved. 照片因为相机移动而模糊了。" },
    { word: "superior", meaning: "a.更好的;占优势的;更高的", example: "This product is superior in quality to the others. 这个产品的质量优于其他产品。" },
    { word: "superior to", meaning: "比…更好;更胜一筹", example: "Her skills are superior to those of her peers. 她的技能比同龄人更胜一筹。" },
    { word: "take over", meaning: "占上风;取而代之;接管;接手", example: "The new manager will take over next week. 新经理将于下周接手。" },
    { word: "inaction", meaning: "n.无行动;不采取措施", example: "The government's inaction led to further problems. 政府的不作为导致了更多问题。" },
    { word: "conflict with", meaning: "与…冲突或抵触", example: "His schedule conflicts with the meeting time. 他的日程与会议时间冲突。" },
    { word: "labour", meaning: "n.劳动者;体力劳动 vi.奋斗", example: "The workers went on strike for better labour conditions. 工人们为争取更好的劳动条件而罢工。" },
    { word: "leather", meaning: "n.皮革;[pl.]皮衣;皮外套", example: "He bought a new leather jacket. 他买了一件新的皮夹克。" },
    { word: "lever", meaning: "n.操纵杆;杠杆", example: "Pull the lever to start the machine. 拉动操纵杆启动机器。" },
    { word: "panel", meaning: "n.控制板;仪表盘;专家咨询组", example: "The control panel is located on the wall. 控制板位于墙上。" },
    { word: "inch", meaning: "n.英寸(等于2.54厘米)", example: "The screen measures 15 inches diagonally. 屏幕对角线长度为15英寸。" },
    { word: "backwards", meaning: "ad.向后;倒着;往回", example: "He took a step backwards to avoid the puddle. 他向后退了一步以避开水坑。" },
    { word: "grip", meaning: "vt.&vi.紧握;抓紧", example: "She gripped the railing tightly as she climbed the stairs. 她爬楼梯时紧紧抓住栏杆。" },
    { word: "hazy", meaning: "a.模糊的;朦胧的;困惑的", example: "The distant mountains were hazy in the morning fog. 远处的山在晨雾中显得朦胧。" },
    { word: "niece", meaning: "n.侄女;外甥女", example: "My niece loves to play with dolls. 我的侄女喜欢玩娃娃。" },
    { word: "fetch", meaning: "vt.(去)拿来;(去)请来", example: "The dog fetched the ball and brought it back. 狗把球叼了回来。" },
    { word: "handkerchief", meaning: "n.手帕;纸巾", example: "He offered her a handkerchief to dry her tears. 他递给她一块手帕擦眼泪。" },
    { word: "lamp", meaning: "n.灯;台灯", example: "She turned on the lamp to read her book. 她打开台灯看书。" },
    { word: "turn out", meaning: "关掉;熄灭;在场;使朝外", example: "Please turn out the lights before leaving. 离开前请关灯。" },
    { word: "pace", meaning: "n.速度;步伐 v.确定速度", example: "She walked at a slow pace to enjoy the scenery. 她放慢脚步欣赏风景。" },
    { word: "fall away", meaning: "(逐渐)减少;消失", example: "Support for the idea began to fall away. 对这个想法的支持开始减少。" },
    { word: "division", meaning: "n.分开;分隔;差异;除(法)", example: "The division of labor improved efficiency. 分工提高了效率。" },
    { word: "puff", meaning: "n.(烟/气等)一缕;少量;喘息", example: "A puff of smoke rose from the chimney. 一缕烟从烟囱升起。" },
    { word: "urge", meaning: "n.强烈的欲望;冲动 vt.催促", example: "He felt an urge to travel and explore new places. 他有一种去旅行和探索新地方的冲动。" },
    { word: "have an urge to", meaning: "有强烈的欲望做某事", example: "She had an urge to call her old friend. 她有一种给老朋友打电话的冲动。" },
    { word: "random", meaning: "a.随机的;不可思议的", example: "The computer generated a random number. 计算机生成了一个随机数。" },
    { word: "maximum", meaning: "a.最大极限的 n.最大量", example: "The maximum capacity of the room is 50 people. 房间的最大容量是50人。" },
    { word: "explode", meaning: "vi.&vt.爆炸;爆破", example: "The fireworks exploded in the night sky. 烟花在夜空中爆炸。" },
    { word: "jolt", meaning: "n.震动;摇晃;颠簸 v.使震动", example: "The bus came to a sudden stop with a jolt. 公交车突然颠簸着停了下来。" },
    { word: "flip", meaning: "v.(使)快速翻转;(手指)轻抛", example: "He flipped the coin to make a decision. 他抛硬币做决定。" },
    { word: "stun", meaning: "vt.使震惊，使昏迷", example: "The news stunned everyone in the room. 这个消息震惊了房间里的所有人。" },
    { word: "mud", meaning: "n.泥;泥浆", example: "After the rain, the path was covered in mud. 雨后，小路上满是泥浆。" },
    { word: "overstatement", meaning: "n.夸大;夸张", example: "Saying it's the best movie ever is an overstatement. 说这是有史以来最好的电影有些夸张。" },
    { word: "iconic", meaning: "a.符号的;图标的", example: "The Eiffel Tower is an iconic symbol of Paris. 埃菲尔铁塔是巴黎的标志性象征。" },
    { word: "foundation", meaning: "n.创建;基础;地基", example: "The foundation of the building was laid last year. 这座建筑的地基是去年打下的。" },
    { word: "political", meaning: "a.政治的", example: "The debate focused on political issues. 辩论集中在政治问题上。" },
    { word: "located", meaning: "a.位于", example: "The hotel is located near the beach. 酒店位于海滩附近。" },
    { word: "equator", meaning: "n.赤道", example: "The equator divides the Earth into northern and southern hemispheres. 赤道将地球分为北半球和南半球。" },
    { word: "koala", meaning: "n.考拉;树袋熊", example: "Koalas spend most of their time sleeping in trees. 考拉大部分时间都在树上睡觉。" },
    { word: "barbecue", meaning: "n.(abbr.BBQ)户外烧烤;烤架", example: "We had a barbecue in the backyard last weekend. 上周末我们在后院烧烤。" },
    { word: "bakery", meaning: "n.面包(糕饼)店;面包厂", example: "The bakery sells fresh bread every morning. 面包店每天早上都卖新鲜面包。" },
    { word: "joint", meaning: "n.公共场所;关节 a.联合的", example: "They opened a joint bank account. 他们开了一个联合银行账户。" },
    { word: "butcher", meaning: "n.肉贩;屠夫;刽子手", example: "The butcher prepared the meat for the customer. 肉贩为顾客准备了肉。" },
    { word: "premier", meaning: "a.最著名的;第一的 n.总理", example: "The premier addressed the nation on television. 总理在电视上向全国发表讲话。" },
    { word: "herb", meaning: "n.药草;香草;草本", example: "She grows herbs in her kitchen garden. 她在菜园里种植香草。" },
    { word: "dim sim", meaning: "(特指澳大利亚的)点心", example: "Dim sim is a popular snack in Australia. 点心在澳大利亚是一种受欢迎的小吃。" },
    { word: "hollow", meaning: "a.中空的;空心的", example: "The tree trunk was hollow inside. 树干内部是空心的。" },
    { word: "vibrate", meaning: "vt.&vi.(使)振动", example: "The phone vibrated on the table. 手机在桌子上振动。" },
    { word: "horn", meaning: "n.(乐器)号", example: "He played the horn in the school band. 他在学校乐队中演奏号。" },
    { word: "pitch", meaning: "n.音高", example: "She has a perfect pitch and can identify any note. 她有绝对音感，能识别任何音符。" },
    { word: "straightforward", meaning: "a.坦率的;简单的", example: "The instructions were straightforward and easy to follow. 说明书简单易懂。" },
    { word: "slogan", meaning: "n.标语;口号", example: "The company's slogan is 'Quality First'. 公司的口号是'质量第一'。" },
    { word: "minister", meaning: "n.部长;大臣;外交使节", example: "The minister announced new policies to support education. 部长宣布了支持教育的新政策。" },
    { word: "prime minister", meaning: "首相;总理", example: "The prime minister met with foreign leaders. 首相会见了外国领导人。" },
    { word: "frog", meaning: "n.蛙;青蛙", example: "The frog jumped into the pond. 青蛙跳进了池塘。" },
    { word: "arrow", meaning: "n.箭;箭头", example: "Follow the arrows to find the exit. 跟随箭头找到出口。" },
    { word: "entitle", meaning: "vt.给…命名;使享有权利", example: "This ticket entitles you to a free drink. 这张票让你可以免费喝一杯。" },
    { word: "getaway", meaning: "n.适合度假的地方", example: "The island is a perfect getaway for relaxation. 这个岛屿是放松的理想度假地。" },
    { word: "dive", meaning: "vi.&n.潜水;跳水;俯冲", example: "She loves to dive into the ocean and explore coral reefs. 她喜欢潜入海洋探索珊瑚礁。" },
    { word: "peak season", meaning: "高峰季节", example: "Hotels are more expensive during peak season. 高峰季节酒店更贵。" },
    { word: "freedom", meaning: "n.自由;不受…影响的状态", example: "Freedom of speech is a fundamental right. 言论自由是一项基本权利。" },
    { word: "domain", meaning: "n.领域;领土;范围", example: "This topic falls within the domain of science. 这个主题属于科学领域。" },
    { word: "sponsor", meaning: "vt.倡议;赞助 n.法案倡议者", example: "The event was sponsored by a local company. 活动由一家当地公司赞助。" },
    { word: "liberty", meaning: "n.自由", example: "The statue symbolizes liberty and justice. 这座雕像象征自由和正义。" },
    { word: "golf", meaning: "n.高尔夫球运动", example: "He plays golf every weekend. 他每周末打高尔夫球。" },
    { word: "strait", meaning: "n.海峡", example: "The ship sailed through the narrow strait. 船驶过狭窄的海峡。" },
    { word: "sample", meaning: "n.样本;样品", example: "The doctor took a blood sample for testing. 医生取了血样进行检测。" },
    { word: "monument", meaning: "n.纪念碑/馆/堂等;历史遗迹", example: "The monument was built to honor the heroes. 这座纪念碑是为纪念英雄而建的。" },
    { word: "a flock of", meaning: "—群(羊或鸟)", example: "A flock of birds flew across the sky. 一群鸟飞过天空。" },
    { word: "distribution", meaning: "n.分布;分配;分发", example: "The distribution of resources was fair. 资源分配是公平的。" },
    { word: "pouch", meaning: "n.育儿袋;小袋子;荷包", example: "The kangaroo carries its baby in a pouch. 袋鼠用育儿袋携带幼崽。" },
    { word: "temporary", meaning: "a.暂时的;短暂的", example: "He found a temporary job while searching for a permanent one. 他在找长期工作时找到了一份临时工作。" },
    { word: "phase", meaning: "n.阶段;时期", example: "The project is in its final phase. 项目处于最后阶段。" },
    { word: "trunk", meaning: "n.树干", example: "The elephant used its trunk to pick up food. 大象用鼻子捡食物。" },
    { word: "licensed", meaning: "a.得到正式许可的", example: "Only licensed drivers can operate the vehicle. 只有有驾照的司机才能驾驶这辆车。" },
    { word: "license", meaning: "vt.批准;许可 n.许可证", example: "You need a license to fish in this lake. 你需要许可证才能在这个湖里钓鱼。" },
    { word: "session", meaning: "n.—场;一段时间;会议", example: "The training session lasted two hours. 培训持续了两个小时。" },
    { word: "frequency", meaning: "n.发生率;重复率;频率", example: "The frequency of earthquakes has increased. 地震的频率增加了。" },
    { word: "violent", meaning: "a.暴力的;猛烈的", example: "The movie contains violent scenes. 电影包含暴力场景。" },
    { word: "violence", meaning: "n.暴力;暴行", example: "The community is working to reduce violence. 社区正在努力减少暴力。" },
    { word: "nest", meaning: "n.巢穴;鸟窝;秘密窝点", example: "The bird built a nest in the tree. 鸟在树上筑巢。" },
    { word: "mammal", meaning: "n.哺乳动物", example: "Whales are the largest mammals in the ocean. 鲸鱼是海洋中最大的哺乳动物。" },
    { word: "biology", meaning: "n.生理;生物学", example: "She is studying biology at university. 她在大学学习生物学。" },
    { word: "hatch", meaning: "vi.孵出 vt.使孵出;策划", example: "The eggs will hatch in about two weeks. 蛋大约两周后会孵化。" },
    { word: "capacity", meaning: "n.能力;容量", example: "The stadium has a capacity of 50,000 people. 体育场可容纳5万人。" },
    { word: "a handful of", meaning: "少数人(或物);一把(的量)", example: "Only a handful of people attended the meeting. 只有少数人参加了会议。" },
    { word: "fence", meaning: "n.栅栏;围栏", example: "They built a fence around the garden. 他们在花园周围建了栅栏。" },
    { word: "prison", meaning: "n.监狱;监禁", example: "He was sentenced to five years in prison. 他被判处五年监禁。" },
    { word: "grand", meaning: "a.大;宏大的", example: "The grand hall was decorated for the ceremony. 大厅为仪式装饰得宏伟壮观。" },
    { word: "tale", meaning: "n.故事;叙述", example: "She told a tale of adventure and bravery. 她讲了一个关于冒险和勇敢的故事。" },
    { word: "merchant", meaning: "n.商人;批发商 a.海上货运的", example: "The merchant sold goods from distant lands. 商人出售来自遥远国度的商品。" },
    { word: "set sail", meaning: "起航;开航", example: "The ship set sail at dawn. 船在黎明时起航。" },
    { word: "extend", meaning: "vt.扩展;使伸长;延长", example: "They decided to extend their vacation by a week. 他们决定将假期延长一周。" },
    { word: "negotiate", meaning: "vt.商定;达成协议 vi.谈判", example: "The two countries negotiated a peace treaty. 两国谈判达成了和平条约。" },
    { word: "fleet", meaning: "n.舰队;机群;车队", example: "The company owns a fleet of delivery trucks. 公司拥有一支送货卡车车队。" },
    { word: "behold", meaning: "vt.看;看见", example: "Behold the beauty of the sunset! 看那日落的美丽！" },
    { word: "league", meaning: "n.等级;水平;联合会;联赛", example: "The team plays in the national league. 球队参加全国联赛。" },
    { word: "in a league of one's own", meaning: "独领风骚", example: "Her talent puts her in a league of her own. 她的才华让她独领风骚。" },
    { word: "royal", meaning: "a.皇家的;王室的;高贵的", example: "The royal family attended the ceremony. 王室成员出席了仪式。" },
    { word: "spice", meaning: "n.(调味)香料", example: "She added some spice to the soup for flavor. 她在汤里加了一些香料调味。" },
    { word: "withdraw", meaning: "vi.＆vt.(使)撤回;撤离", example: "He decided to withdraw from the competition. 他决定退出比赛。" },
    { word: "withdraw from", meaning: "退出;撤回", example: "The army withdrew from the area. 军队从该地区撤出。" },
    { word: "channel", meaning: "n.航道;海峡;频道", example: "She changed the channel to watch the news. 她换频道看新闻。" },
    { word: "maritime", meaning: "a.海的;海运的;海事的", example: "The country has a strong maritime tradition. 这个国家有强大的海运传统。" },
    { word: "bond", meaning: "n.纽带;关系 v.增强信任关系", example: "The bond between the two friends was unbreakable. 两位朋友之间的纽带牢不可破。" },
    { word: "in hand", meaning: "在手头;可供使用", example: "We have enough resources in hand to complete the project. 我们手头有足够的资源完成项目。" },
    { word: "politics", meaning: "n.政治;政治观点", example: "He has strong opinions about politics. 他对政治有强烈的看法。" },
    { word: "profession", meaning: "n.职业;行业", example: "Teaching is a noble profession. 教学是一个崇高的职业。" },
    { word: "tournament", meaning: "n.锦标赛;联赛", example: "The tennis tournament attracted top players. 网球锦标赛吸引了顶尖选手。" },
    { word: "mixture", meaning: "n.混合;结合体;混合物", example: "The cake batter is a mixture of flour, eggs, and sugar. 蛋糕面糊是面粉、鸡蛋和糖的混合物。" },
    { word: "laptop", meaning: "n.笔记本电脑;便携式电脑", example: "He uses his laptop for work and entertainment. 他用笔记本电脑工作和娱乐。" },
    { word: "coverage", meaning: "n.新闻报道;覆盖范围", example: "The event received extensive media coverage. 活动得到了媒体的广泛报道。" },
    { word: "press conference", meaning: "记者招待会;新闻发布会", example: "The mayor held a press conference to address the issue. 市长召开新闻发布会讨论这个问题。" },
    { word: "applaud", meaning: "vt.＆vi.鼓掌 vt.称赞;赞赏", example: "The audience applauded after the performance. 观众在表演结束后鼓掌。" },
    { word: "tax", meaning: "vt.对…征税 n.税;税款", example: "The government taxes income and property. 政府对收入和财产征税。" },
    { word: "manned", meaning: "a.有人控制的;需人操纵的", example: "The first manned mission to the moon was in 1969. 第一次载人登月任务是在1969年。" },
    { word: "submersible", meaning: "n.潜水器;可潜船", example: "The submersible explored the ocean depths. 潜水器探索了海洋深处。" },
    { word: "underwater", meaning: "ad.在水下 a.水下的", example: "The divers explored the underwater cave. 潜水员探索了水下洞穴。" },
    { word: "coral", meaning: "n.珊瑚", example: "The coral reef is home to many marine species. 珊瑚礁是许多海洋生物的家园。" },
    { word: "migration", meaning: "n.迁移;迁徙;移居", example: "Bird migration happens twice a year. 鸟类迁徙每年发生两次。" },
    { word: "directory", meaning: "n.名录;电话号码簿", example: "She looked up his number in the directory. 她在电话簿中查找他的号码。" },
    { word: "meanwhile", meaning: "ad.与此同时;两方面对比之下", example: "She was cooking dinner; meanwhile, he set the table. 她在做晚餐，与此同时，他摆好了餐具。" },
    { word: "exploit", meaning: "vt.开发;利用;剥削", example: "The company was accused of exploiting workers. 公司被指控剥削工人。" },
    { word: "gallon", meaning: "n.加仑(容积单位)", example: "The car's fuel tank holds 12 gallons. 汽车的油箱可装12加仑油。" },
    { word: "murder", meaning: "vt.谋杀;凶杀 n.谋杀;凶杀", example: "The detective solved the murder case. 侦探侦破了谋杀案。" },
    { word: "mercy", meaning: "n.仁慈;宽恕;恩惠", example: "The judge showed mercy to the first-time offender. 法官对初犯者表现出仁慈。" },
    { word: "possession", meaning: "n.[pl.]个人财产;拥有;控制", example: "He lost all his possessions in the fire. 他在火灾中失去了所有财产。" },
    { word: "opponent", meaning: "n.反对者;对手;竞争者", example: "She defeated her opponent in the debate. 她在辩论中击败了对手。" },
    { word: "log", meaning: "vt.把…载入记录 n.正式记录", example: "The captain logged the ship's position daily. 船长每天记录船的位置。" },
    { word: "marine", meaning: "a.海的;海产的;海生的", example: "Marine life is diverse and fascinating. 海洋生物多样且迷人。" },
    { word: "arrest", meaning: "n.逮捕;拘留 vt.逮捕;拘留", example: "The police made an arrest in the case. 警方在案件中逮捕了一人。" }
];